In [ ]:
!pip install transformers

In [ ]:
import tensorflow as tf
from transformers import TFAutoModel, AutoTokenizer

In [ ]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
tokenizer(['Hello world', 'Hi how are you'])

# {
#   'input_ids': [[101, 7592, 2088, 102], [101, 7632, 2129, 2024, 2017, 102]],
#   'token_type_ids': [[0, 0, 0, 0], [0, 0, 0, 0, 0, 0]],
#   'attention_mask': [[1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]
# }


{'input_ids': [[101, 7592, 2088, 102], [101, 7632, 2129, 2024, 2017, 102]], 'token_type_ids': [[0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

In [ ]:
inputs = tokenizer(['Hello world', 'Hi how are you'],
                   padding=True,
                   truncation=True,
                   return_tensors='tf')
inputs

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 101, 7592, 2088,  102,    0,    0],
       [ 101, 7632, 2129, 2024, 2017,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
output = model(inputs)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-0.16888352,  0.13606349, -0.13940042, ..., -0.62511253,
          0.05217263,  0.36714536],
        [-0.36327422,  0.1412186 ,  0.87998784, ...,  0.10433061,
          0.28875765,  0.37267935],
        [-0.69859403, -0.6987974 ,  0.06450184, ..., -0.22103682,
          0.00986876, -0.5939795 ],
        [ 0.83098316,  0.12366714, -0.15119052, ...,  0.10309655,
         -0.6779263 , -0.26285207],
        [-0.40266624, -0.01928265,  0.57325   , ..., -0.20656838,
          0.02338585,  0.20126288],
        [-0.6228404 , -0.2745352 ,  0.181176  , ..., -0.12944853,
         -0.03839105, -0.05733202]],

       [[ 0.09286544, -0.02636395, -0.12239335, ..., -0.21063557,
          0.17386365,  0.17250964],
        [ 0.40742013, -0.0593101 ,  0.5523468 , ..., -0.6790565 ,
          0.6555739 , -0.29456532],
        [-0.21155277, -0.68586326, -0.46280688, ...,  0.15278542